server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

process-engine:
  persistence:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  retry:
    max-attempts: 3
    base-interval: 5s
    max-interval: 5m
